# To build the application for production (with full data set), use the command line below:
# bundle exec jekyll serve --config _config.yml,_config.prod.yml -d ./docs
data_dir: _data_prod

# Enable the local storage cache for auto-suggestions in production
disable-auto-suggest-cache: 0