# To build the application for production (with full data set), use the command line below:
# bundle exec jekyll serve --config _config.yml,_config.prod.yml -d ./docs
data_dir: _data_prod

# Current hosting on Github Pages requires an additional /remedes before all URLs
baseurl: "/remedes"