# To build the application for production (with full data set), use the command line below:
# bundle exec jekyll serve --config _config.yml,_config.prod.yml -d ./docs
data_dir: _data_prod

# Current hosting on Github Pages requires an additional /remedes before all URLs
baseurl: "/remedes"

# Enable the local storage cache for auto-suggestions in production
disable-auto-suggest-cache: 0

# Exclude the following folders from the build to reduce (drastically) the build time
exclude:
  - docs
  - _data_prod/raw
  - _data